# Root dataset path (optional)
path: F:\AASTMT (Bachelor CE)\Semester 10\Senior Project II\Graduation_Project\annotated_data

# Image directories
train: F:\AASTMT (Bachelor CE)\Semester 10\Senior Project II\Graduation_Project\annotated_data\train\images
val: F:\AASTMT (Bachelor CE)\Semester 10\Senior Project II\Graduation_Project\annotated_data\val\images
test: F:\AASTMT (Bachelor CE)\Semester 10\Senior Project II\Graduation_Project\annotated_data\test\images

# Keypoint configuration
kpt_shape: [15, 3]  # 15 keypoints (x, y, visibility)
flip_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

# Number of pose classes
nc: 7

# Class names
names:
  - StepJacks
  - SideToSideReach
  - SideToSideSquad
  - LowPendulum
  - StepOutKnee
  - KneeToElbow
  - Standing
